### ISSUE TITLE
Inventarisatie van alle bestaande bronnen

### ISSUE THREAD

**Issue by ux-fran** [nl-design-system/overheidsbrede-portalen-community#127]
# Todo template inventarisatie:
- [x] Inventariseer welke templates er al zijn? (Meerstappen form (Wmebv), MijnOmgeving, MijnProfiel, Zaakdetail) 
- [x] Inventariseer in welke thema's de templates al zijn gemaakt in Figma.
- [ ] Achterhaal de status van de Figma designs (zijn ze up to date?) 
- - [ ] Meerstappen form (Wmebv form):  Zelf up to date maken (Fran)
- - [ ] Homepage - MijnOmgeving: Roos en navragen bij Rico van der Sloot
- - [ ] Zaakdetailpagina - Roos en navragen bij Rico van der Sloot
- - [ ] MijnProfiel - Rico van der Sloot vragen naar de stand van zaken
- [ ] Maak de templates up to date of zorg ervoor dat ze up to date thema's worden aangeleverd.

#Todo thema inventarisatie:
- [x] Verzamel alle thema figma's (indien die er zijn) (Rijksoverheid, NLDS Paars, Opengemeente (zoals Gemeente Hoekse Waard) en NLPortal (Zoals Den Haag)
- [ ] Achterhaal de status van de thema Figma's
- [ ] Maak de thema's up to date of zorg ervoor de ze up to date worden aangeleverd.

Houdt de stand van zaken bij in de Miro: https://miro.com/app/board/uXjVKi7wpLQ=/?share_link_id=950860234685
