### ISSUE TITLE
Thema Hoeksche Waard  - Maken in Tokenstudio

### ISSUE THREAD

**Issue by ux-fran** [nl-design-system/overheidsbrede-portalen-community#128]
## Description

Om de template van de Overheidsbrede portalen Storybook te voorzien van thema's kan gebruikgemaakt worden van Tokenstudio in Figma. Gevraagd is een Hoeksche Waard thema in Tokenstudio te maken.

## Todo
- [x] Martijn Rietveld vragen of ik de styling inderdaad uit [MijnHW Figma](https://www.figma.com/design/b8GQng7VNPiKedjdd6KDJs/MijnHW?node-id=2-12&t=Oe1kYDv3fMfyxGRh-1) kan halen of dat hij een betere bron weet.
- [x] Thema HW maken in Tokenstudio

## Testen in [Overheidsbrede portalen Figma](https://www.figma.com/design/iZgSIuU8hvH9nw3h7WO1ZY/Overheidsbrede-portalen---Templates?node-id=4587-87333&t=fBOjMM1rNXPjbwPd-1)
- [x] Thema werkt correct in Mijn Profiel

## Ter info:
   - Voorbeeldthema wordt beheerd door Jeffrey en is reeds beschikbaar voor Storybook
   - Rijksoverheid thema wordt beheerd door ?? (Aline Nap en Roos hebben er eentje opgezet voor het thema builder voorbeeld)
   - Hoeksche Waard wordt aangeleverd door Francesca (deze story)
   - NL Portal (Den Haag) wordt voor gemaakt middels code en niet in Tokenstudio gezien dat geen toegevoegde waarde heeft voor het doel van het Storybook project.
