### ISSUE TITLE
Expandable section component: Development - Mijn Profiel Template

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/overheidsbrede-portalen-community#181]
# Description

### Resources
- [Design](https://www.figma.com/design/gX3fq7k0uUKC45AJbuItDv/Local---Voorbeeld---Bibliotheek?node-id=1924-298&node-type=canvas&t=ode1BjtdQGMPBmEC-0)
- [Github discussion](https://github.com/orgs/nl-design-system/discussions/344)

### Varianten
Deze varianten zijn niet in scope, maar kunnen we we wel rekening mee houden
- Expandable checkbox group, met enkele checkbox selector

### Tasks
- [x] Clickable button element to expand panel
- [x] Panel element
- [x] Flexible content in button element
- [ ] Toevoegen aan DH library
[update: Aan onze kant is het af maar Youri nodig voor toevoegen aan DH lib. Maar hij is op vacay. 09/12/2024]
