### ISSUE TITLE
Thema Rijksoverheid - Importeren in Tokenstudio (versie Aline Nap) en uittesten in onze figma templates.

### ISSUE THREAD

**Issue by ux-fran** [nl-design-system/overheidsbrede-portalen-community#195]
## Description
Om de template van de Overheidsbrede portalen Storybook te voorzien van thema's kan gebruikgemaakt worden van Tokenstudio in Figma.

Gezien er al een uitgebreide Tokenstudio van Rijksoverheid bestaat vanuit Aline Nap en Roos, zou deze wellicht geschikt kunnen zijn voor het aanleveren van de Token JSON voor de Storybook.

## Todo
- [x] Tokenstudio Rijksoverheid navragen bij Roos/Aline
   - antwoord Aline: Ja dat kan, door deze link in te vullen via TS: [https://raw.githubusercontent.com/nl-design-system/rijkshuisstijl-community/refs/heads/al[…]writes/proprietary/design-tokens/figma/figma.tokens.json](https://raw.githubusercontent.com/nl-design-system/rijkshuisstijl-community/refs/heads/aline/overwrites/proprietary/design-tokens/figma/figma.tokens.json)
Dan kun je ze alleen niet aanpassen. Als je dat wilt kun je de raw code kopieren als file en in TS zetten via import file. 
- [x] Aline's Tokenstudio file importeren.
- [x] Daar waar nodig, dingen fixen?

## Testen in [Overheidsbrede portalen Figma](https://www.figma.com/design/iZgSIuU8hvH9nw3h7WO1ZY/Overheidsbrede-portalen---Templates?node-id=4587-87333&t=fBOjMM1rNXPjbwPd-1)
- [x] Thema werkt correct in Meerstappen formulier WMEBV

## Ter info:
   - Voorbeeldthema wordt beheerd door Jeffrey en is reeds beschikbaar voor Storybook
   - Rijksoverheid thema wordt beheerd door Aline? (Aline Nap en Roos hebben er eentje opgezet voor het thema builder voorbeeld) (deze story)
   - Hoeksche Waard wordt aangeleverd door Francesca
   - NL Portal (Den Haag) wordt voor gemaakt middels code en niet in Tokenstudio gezien dat geen toegevoegde waarde heeft voor het doel van het Storybook project.
