### ISSUE TITLE
Overheidsbrede portalen Storybook - Validatie met leveranciers

### ISSUE THREAD

**Issue by ux-fran** [nl-design-system/overheidsbrede-portalen-community#196]
Vanuit de opdracht is samenwerking met leveranciers gewenst om te valideren wat gewenst is betreft de Storybook.

Met wie, wanneer en hoe willen we wat valideren?

# Todo:
- [x] Fran en Bryan prikken momenten en maken plan voor samenwerking met leveranciers 
   - Wanneer wordt een samenwerking als voldoende bestempeld?
   - Hoe pakken we het aan / wat willen we eruit halen / hoe documenteren we het
   - Planning maken
- [x] Update mail naar Chris en Vincent incl. lijstje benaderde leveranciers met oproep om aan te vullen indien gewenst.
- [x] Fran/Bryan nodigen leveranciers uit voor samenwerking per mail/slack
- [x] Alle digitale koffietjes zijn vastgelegd met een MS Teams agenda-uitnodiging 

---
## Wat
- [x] Presenteren eerste opzet/idee
- [x] Achterhalen wat zij anders / nog meer zouden willen hebben

   - Notule bijhouden/documenteren    
   - Wensen inplannen en pakken of parkeren in de [Groeivariant](https://github.com/nl-design-system/overheidsbrede-portalen-community/issues/193)

## Hoe 
Online bijeenkomsten inividueel
